# Application Config
spring:
  application:
    name: springboot-database-profiles-elsticsearch-appender
  profiles:
    active:
     - postgres
     #- oracle  
     
server:  port: 9385
  
  